# Generated by Django 5.0.1 on 2026-03-05 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WEATHER', 'Weather'), ('AQI', 'AQI'), ('CURFEW', 'Curfew')], max_length=20)),
                ('zone', models.CharField(max_length=100)),
                ('severity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
