# Generated by Django 5.0.1 on 2026-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='reported_by',
            field=models.CharField(blank=True, default='system', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('WEATHER', 'Weather'), ('AQI', 'AQI'), ('CURFEW', 'Curfew'), ('STORM', 'Storm'), ('FLOOD', 'Flood'), ('HEAT', 'Extreme Heat'), ('STRIKE', 'Strike'), ('ZONE_CLOSURE', 'Zone Closure')], max_length=20),
        ),
    ]
