# Generated by Django 5.0.1 on 2026-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_event_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[
                    ("WEATHER", "Weather"),
                    ("AQI", "AQI"),
                    ("CURFEW", "Curfew"),
                    ("STORM", "Storm"),
                    ("FLOOD", "Flood"),
                    ("HEAT", "Extreme Heat"),
                    ("STRIKE", "Strike"),
                    ("ZONE_CLOSURE", "Zone Closure"),
                    ("DELIVERY_CANCELLED", "Delivery Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
