# Generated by Django 5.0.1 on 2026-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
