# Generated by Django 5.0.1 on 2026-03-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_delivery_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="cancellation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RAIN", "Heavy Rain"),
                    ("CURFEW", "Curfew/Lockdown"),
                    ("TRAFFIC", "Severe Traffic"),
                    ("OTHER", "Other (View custom reason)"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
