# Generated by Django 5.0.1 on 2026-03-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_delivery_cancellation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="agent_can_keep_items",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="delivery",
            name="retail_retry_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ASSIGNED", "Assigned"),
                    ("RETRYING", "Retrying (3-day window)"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
