# Generated by Django 5.0.1 on 2026-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0004_delivery_agent_can_keep_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food Delivery"),
                    ("GROCERY", "Grocery"),
                    ("PARCEL", "Parcel/Courier"),
                ],
                default="FOOD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ASSIGNED", "Assigned"),
                    ("ONGOING", "In Progress"),
                    ("RETRYING", "Retrying (3-day window)"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
