# Generated by Django 5.0.1 on 2026-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0005_delivery_category_alter_delivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="category",
            field=models.CharField(
                choices=[
                    ("QUICK_COMMERCE", "Quick Commerce (Food/Instant)"),
                    ("GROCERY", "Grocery"),
                    ("PARCEL", "Parcel (Ecommerce)"),
                ],
                default="FOOD",
                max_length=20,
            ),
        ),
    ]
