# Generated by Django 5.0.1 on 2026-03-08 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
        ('policies', '0002_policy_created_at_policy_next_payment_date_and_more'),
        ('users', '0003_worker_latitude_worker_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_reason',
            field=models.CharField(choices=[('WEATHER', 'Weather Disruption'), ('RAIN', 'Heavy Rain'), ('HEAT', 'Extreme Heat'), ('AQI', 'Air Quality'), ('POLLUTION', 'Severe Pollution'), ('STORM', 'Storm/Cyclone'), ('FLOOD', 'Flood'), ('CURFEW', 'Curfew'), ('STRIKE', 'Strike'), ('ZONE_CLOSURE', 'Zone Closure')], default='WEATHER', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='fraud_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_APPROVED', 'Auto Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('FRAUD_FLAGGED', 'Fraud Flagged')], default='PENDING', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('worker', 'claim_date', 'claim_reason')},
        ),
    ]
