# Generated by Django 5.0.1 on 2026-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_alter_claim_options_claim_claim_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="claim_reason",
            field=models.CharField(
                choices=[
                    ("WEATHER", "Weather Disruption"),
                    ("RAIN", "Heavy Rain"),
                    ("HEAT", "Extreme Heat"),
                    ("AQI", "Air Quality"),
                    ("POLLUTION", "Severe Pollution"),
                    ("STORM", "Storm/Cyclone"),
                    ("FLOOD", "Flood"),
                    ("CURFEW", "Curfew"),
                    ("STRIKE", "Strike"),
                    ("ZONE_CLOSURE", "Zone Closure"),
                    ("DELIVERY_CANCELLED", "Delivery Cancelled"),
                ],
                default="WEATHER",
                max_length=20,
            ),
        ),
    ]
