# Generated by Django 5.0.1 on 2026-03-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_alter_claim_claim_reason"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="claim",
            unique_together=set(),
        ),
    ]
