# Generated by Django 5.0.1 on 2026-03-07 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_otp_worker_is_verified_worker_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REVIEW', 'Manual Review Required')], default='PENDING', max_length=10)),
                ('forensics_score', models.IntegerField(default=0)),
                ('ocr_score', models.IntegerField(default=0)),
                ('platform_score', models.IntegerField(default=0)),
                ('cross_check_score', models.IntegerField(default=0)),
                ('total_trust_score', models.IntegerField(default=0)),
                ('forensics_report', models.JSONField(default=dict)),
                ('extracted_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='users.worker')),
            ],
        ),
    ]
