# Generated by Django 5.0.1 on 2026-03-07 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="next_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("UPI_AUTOPAY", "UPI AutoPay"),
                    ("MANUAL", "Manual Payment"),
                    ("WALLET", "Wallet"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard Protection"),
                    ("PREMIUM", "Premium Protection"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="policy_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="policy",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PENDING", "Pending Payment"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
