# Generated by Django 5.0.1 on 2026-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_policy_created_at_policy_next_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Zomato", "Zomato"),
                    ("Swiggy", "Swiggy"),
                    ("Blinkit", "Blinkit"),
                    ("Amazon", "Amazon"),
                    ("Flipkart", "Flipkart"),
                    ("Zepto", "Zepto"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
