# Generated by Django 5.0.1 on 2026-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0002_policy_created_at_policy_next_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic Plan"),
                    ("PRO", "Pro Plan"),
                    ("PREMIUM_PLUS", "Premium Plus"),
                ],
                default="BASIC",
                max_length=20,
            ),
        ),
    ]
