# Generated by Django 5.0.1 on 2026-04-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='plan_type',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('STANDARD', 'Standard Plan'), ('PRO', 'Pro Plan'), ('PREMIUM_PLUS', 'Premium Plus')], default='BASIC', max_length=20),
        ),
    ]
