# Generated by Django 5.0.1 on 2026-03-05 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('platform', models.CharField(choices=[('Zomato', 'Zomato'), ('Swiggy', 'Swiggy'), ('Blinkit', 'Blinkit'), ('Amazon', 'Amazon')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('avg_daily_income', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
