# Generated by Django 5.0.1 on 2026-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="worker",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="partner_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Bike", "Bike"),
                    ("Scooter", "Scooter"),
                    ("Cycle", "Cycle"),
                    ("Car", "Car"),
                ],
                default="Bike",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="weekly_earnings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worker",
            name="working_days",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="worker",
            name="working_hours",
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name="worker",
            name="avg_daily_income",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="worker",
            name="platform",
            field=models.CharField(
                choices=[
                    ("Zomato", "Zomato"),
                    ("Swiggy", "Swiggy"),
                    ("Blinkit", "Blinkit"),
                    ("Amazon", "Amazon"),
                    ("Flipkart", "Flipkart"),
                    ("Zepto", "Zepto"),
                ],
                max_length=20,
            ),
        ),
    ]
