# Generated by Django 5.0.1 on 2026-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_worker_is_verified_worker_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
