# Generated by Django 5.0.1 on 2026-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_worker_latitude_worker_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="pricing_plan",
            field=models.CharField(default="STANDARD", max_length=20),
        ),
        migrations.AddField(
            model_name="worker",
            name="renewal_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="security_key",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
