# Generated by Django 5.0.1 on 2026-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_worker_pricing_plan_worker_renewal_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="govt_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
