# Generated by Django 5.0.1 on 2026-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_worker_govt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
