# Generated by Django 5.0.1 on 2026-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_worker_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="total_cancelled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="worker",
            name="total_deliveries",
            field=models.IntegerField(default=0),
        ),
    ]
