# Generated by Django 5.0.1 on 2026-03-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_worker_total_cancelled_worker_total_deliveries"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="wallet_savings",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
