# Generated by Django 5.0.1 on 2026-03-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_worker_wallet_savings"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
