# Generated by Django 5.0.1 on 2026-03-27 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_worker_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPlatformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('partner_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='Bangalore', max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('weekly_earnings', models.IntegerField()),
                ('total_deliveries', models.IntegerField(default=50)),
                ('rating', models.FloatField(default=4.5)),
                ('vehicle_type', models.CharField(default='Bike', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
