# Generated by Django 5.0.1 on 2026-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_worker_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
