# Generated by Django 5.0.1 on 2026-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_worker_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="aadhar_back",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/aadhar/"),
        ),
        migrations.AddField(
            model_name="worker",
            name="aadhar_front",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/aadhar/"),
        ),
        migrations.AddField(
            model_name="worker",
            name="is_aadhar_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="is_pan_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worker",
            name="kyc_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="pan_card",
            field=models.ImageField(blank=True, null=True, upload_to="kyc/pan/"),
        ),
    ]
