# Generated by Django 5.0.1 on 2026-03-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_worker_aadhar_back_worker_aadhar_front_and_more"),
        ("users", "0012_mockplatformdata_pan_number"),
    ]

    operations = []
