# Generated by Django 5.0.1 on 2026-04-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20260330_1255'),
        ('users', '0013_merge_20260330_2247'),
    ]

    operations = [
    ]
