# Generated by Django 5.0.1 on 2026-04-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_worker_bank_account_number_worker_bank_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
